### PR TITLE
Add createTransfer

### PR DESCRIPTION
**Pull request by kanato-masayoshi**
Add support for `POST /v2/home/money/transfer`  

P.S.
@hotchemi
Should I ask your review for every PR though now I have push permission to this repository?  
If you don't have enough time to conduct a review, I will merge the PRs myself.

### CODE REVIEW

**Review by hotchemi — APPROVED** [review]
👍

**Comment by hotchemi** [comment]
@cosnomi thank you! please assign me but you don't have to wait my review~
I'll automate release process on CI~hold on!

**Comment by kanato-masayoshi** [comment]
@hotchemi 
OK. I will assign you to PRs. I'll wait for about a day and then merge a PRs myself if no comments from you. Even in that case, you can revert them at any time you realize something wrong.  
And CI is such a nice thing to have. It's really helpful. Thanks.

**Comment by hotchemi** [comment]
@cosnomi 2.0.0 is available on npm and we've automated release process on TravisCI! When you push tag on GitHub TravisCI will publish new version to npm~
https://github.com/hotchemi/zaim.js/pull/4

**Comment by kanato-masayoshi** [comment]
All right. Thank you.

**Pull request merged**
