### PR TITLE
Update endpoints, params, and request methods for api v2

### PR DESCRIPTION
**Pull request by kanato-masayoshi**
zaim.js is very useful, but due to the recent API update, it is outdated. Here I fixed some of the endpoints, parameters, and request methods so that zaim.js can work with the new API.  
This pull request does not include newly-added API endpoints like "POST /v2/home/money/transfer". I am willing to work also on them later if you are ready to accept the pull request. (I'm slightly worried that you ignore this pull request as you are no longer interested in zaim.js.)  

P.S.
I don't mind reverting all double quotation marks to single ones. They all are altered by the formatter. I have a slight preference for single ones, but I don't mind.

### CODE REVIEW

**Comment by hotchemi** [comment]
Thank you! I'll take a look.

**Comment by kanato-masayoshi** [comment]
@hotchemi Is there anything you are concerned about? It's not my intention to rush you, but if you have some questions about this PR, feel free to ask me.

**Comment by hotchemi** [comment]
Sorry for the late~! I'll merge.

**Review by hotchemi — APPROVED** [review]
LGTM

**Comment by hotchemi** [comment]
@cosnomi Do you need new version release? 👀And..if you're willing to can I add you as a collaborator? As you know I created this library a few years ago and it's now not well maintained, if you're using it that'd be awesome~!

**Comment by kanato-masayoshi** [comment]
@hotchemi This version is no longer compatible with older ones, so the new version release is recommended. and I would appreciate if you could add me as a collaborator. Thanks.

**Pull request merged**
